### ISSUE TITLE
Unable to start FauxMo because of UDP port binding

### ISSUE THREAD

**Issue by Sawtaytoes** [dsandor/fauxmojs#9]
When starting FauxMo using the `example-updated` method, this is what I see in the console:

```js
started..
updated..
D:\Projects\Personal\FauxMo-Controller\node_modules\fauxmojs\lib\discoveryService.js:101
        throw err;
        ^

Error: bind EADDRINUSE 0.0.0.0:1900
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1045:20)
    at _handle.lookup (dgram.js:242:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```

I'm using Windows 10 64-bit.

This line is the issue in `discoveryService.js`:
```js
udpServer.bind(1900);
```

I was able to temporarily fix it by changing `1900` to `1901`.

What's causing this port to already be in use? Is it possible I already have an SSDP server running?

When I do `netstat -anobp udp`, I see these:

```shell
  Proto  Local Address          Foreign Address        State           PID
 [svchost.exe]
  UDP    0.0.0.0:1900           *:*                                    94576
 [svchost.exe]
  UDP    127.0.0.1:1900         *:*                                    5248
  SSDPSRV
```

**Comment by Sawtaytoes** [comment]
I believe this issue is resolved with this pull request: https://github.com/dsandor/fauxmojs/pull/8

Is there a reason it hasn't been pulled in yet?

**Comment by dsandor** [comment]
I merged it in.  Sorry, wife had twins.. life happened.
